name: awake
description: A neumorphic themed digital calculator which has keyboard and dark mode support
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.7.0
  flutter: 3.32.5

dependencies:
  alarm: ^5.1.4
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_inset_box_shadow_update: ^0.0.1
  lottie: ^3.3.1
  permission_handler: ^12.0.1
  shared_preferences: ^2.5.3
  sqflite: ^2.3.0
  path: ^1.9.0
  path_provider: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/fonts/
    - assets/lottie/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
