name: Build and Deploy Releases

on:
  workflow_dispatch:
    inputs:
      version_number:
        description: 'Release Version Number'
        required: true
        type: string

env:
  FLUTTER_CHANNEL: "stable"
  RUBY_VERSION: "3.2.2"

jobs:
  build_android:
    name: Build Android
    runs-on: ubuntu-latest
    timeout-minutes: 40
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
          bundler-cache: true
          working-directory: 'android'

      - name: Run Flutter tasks
        uses: subosito/flutter-action@v2.16.0
        with:
          flutter-version-file: 'pubspec.yaml'
          channel: ${{ env.FLUTTER_CHANNEL }}
          cache: true

      - name: Create google_service_account.json
        run: |
          echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT_BASE64 }}" | base64 --decode > google_service_account.json

      - name: Create key.jks
        run: |
          echo "${{ secrets.ANDROID_KEYSTORE_FILE_BASE64 }}" | base64 --decode > android/key.jks

      - name: Create key.properties
        run: |
          cat <<EOF > android/key.properties
          storePassword=${{ secrets.ANDROID_KEY_STORE_PASSWORD }}
          keyPassword=${{ secrets.ANDROID_KEY_STORE_PASSWORD }}
          keyAlias=upload
          storeFile=../key.jks
          EOF
        env:
          ANDROID_KEY_STORE_PASSWORD: ${{ secrets.ANDROID_KEY_STORE_PASSWORD }}

      - name: Build APK
        uses: maierj/fastlane-action@v3.1.0
        with:
          lane: 'build_apk'
          subdirectory: android
          options: '{ "version_number": "${{ inputs.version_number }}" }'

      - name: Create and Upload Apk Artifact to GitHub Release
        run: |
          if gh release view "${{ inputs.version_number }}" > /dev/null 2>&1; then
            echo "Release '${{ inputs.version_number }}' already exists. Skipping release creation."
          else
            echo "Release '${{ inputs.version_number }}' does not exist. Creating release..."
            gh release create "${{ inputs.version_number }}" --title "Version ${{ inputs.version_number }}" --generate-notes
          fi
          gh release upload ${{ inputs.version_number }} build/app/outputs/flutter-apk/Awake-Android.apk
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Release To Play Store
        uses: maierj/fastlane-action@v3.1.0
        with:
          lane: 'release_play_store'
          subdirectory: android
          options: '{ "version_number": "${{ inputs.version_number }}" }'
        env:
          APP_PACKAGE_NAME: ${{ secrets.APP_PACKAGE_NAME }}
